# Generated by Django 5.0.8 on 2024-08-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="created_by",
        ),
    ]
