# Generated by Django 5.0.8 on 2024-08-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0002_remove_ticket_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="status",
        ),
    ]
