# Generated by Django 5.0.8 on 2024-08-07 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0003_remove_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="assigned_to",
        ),
        migrations.AlterField(
            model_name="aisolution",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_solutions",
                to="ticketing.ticket",
            ),
        ),
    ]
