# Generated by Django 5.0.8 on 2024-08-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0005_ticket_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROGRESS", "In Progress"),
                    ("CLOSED", "Closed"),
                ],
                default="OPEN",
                max_length=11,
            ),
        ),
    ]
